version: '3.8'

services:
  app:
    image: asisgolu95/demo-app:latest
    deploy:
      replicas: 2
    expose:
      - "3000"  # Expose port internally, no need to bind to host port
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Nginx is still available on port 80 on the host machine
      - "443:443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro # Mount SSL certificates
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
